table Dim_Date
	lineageTag: 50a30e66-6e7f-4181-ad36-d2f338af11b3

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1d47aab9-ccb3-4982-9d2b-71a831754c63
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 48a42f9b-fb3d-4063-adea-dc0105884d60
			defaultHierarchy: LocalDateTable_cb2f7f37-58c0-498d-b87c-3c0058123509.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 4cb32cff-a930-4327-b132-70dfb675714c
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 3a7145af-6e72-4e1d-bc0b-66ebbd631858
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: ce15e737-a73d-47f9-b542-61566739e16f
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\tharu\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"date"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Inserted Year" = Table.AddColumn(#"Removed Duplicates", "Year", each Date.Year([date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Year", "Month Name", each Date.MonthName([date]), type text),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Month Name", "Month", each Date.Month([date]), Int64.Type)
				in
				    #"Inserted Month"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

